# generated by datamodel-codegen:
#   filename:  vdjbase-api-openapi3.yaml
#   timestamp: 2024-07-08T11:59:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Ontology(BaseModel):
    id: Optional[str] = Field(
        None, description='CURIE of the concept, encoding the ontology and the local ID'
    )
    label: Optional[str] = Field(
        None, description='Label of the concept in the respective ontology'
    )


class Dataset(BaseModel):
    dataset: Optional[str] = None
    locus: Optional[str] = None
    type: Optional[str] = None


class DatasetsResponse(BaseModel):
    datasets: Optional[List[Dataset]] = None


class SubjectDataset(BaseModel):
    id: Optional[int] = None
    study_name: Optional[str] = None
    subject_identifier: Optional[str] = None
    sample_identifier: Optional[str] = None
    dataset: Optional[str] = None


class SubjectDatasetResponse(BaseModel):
    subject_datasets: Optional[List[SubjectDataset]] = None


class ErrorResponse(BaseModel):
    message: Optional[str] = Field(None, description='Detail about the error')


class SpeciesResponse(BaseModel):
    species: Optional[List[Ontology]] = None
